[package]
name = "lecsicon-db"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
diesel = { version = "2.2.5", features = ["sqlite"] }
dotenvy = "0.15.7"
hunspell-rs = "0.4.0"
inquire = "0.7.5"
