CREATE TABLE IF NOT EXISTS lecsicon (
        id INTEGER NOT NULL,
        word TEXT NOT NULL,
        lemma TEXT,
        tag INTEGER,
        adposition_type BOOLEAN,
        definite BOOLEAN,
        degree INTEGER,
        gender INTEGER,
        mood INTEGER,
        mutation INTEGER,
        name_type INTEGER,
        number INTEGER,
        number_form BOOLEAN,
        number_type INTEGER,
        person INTEGER,
        polarity BOOLEAN,
        polite INTEGER,
        position BOOLEAN,
        possessive BOOLEAN,
        pronoun_type INTEGER,
        relative BOOLEAN,
        style INTEGER,
        tense INTEGER,
        verb_form BOOLEAN,
        PRIMARY KEY (id, word)
);
